version: '3'
services:
  db:
    image: postgres:alpine
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: root
      POSTGRES_DB: default
  memcached:
    image: memcached:alpine
    container_name: memcached
    restart: always
    ports:
      - "11211:11211"